### ISSUE TITLE
Altona v0.12.1 tracker

### ISSUE THREAD

**Issue by q9f** [goerli/altona#17]
Name: v0.12.1 [Altona](https://www.reddit.com/r/ethfinance/comments/guf8lr/daily_general_discussion_june_1_2020/fsil2n8/?context=3)

Tracker:
* [ ] Lighthouse https://github.com/sigp/lighthouse/issues/1182
* [x] Prysm https://github.com/prysmaticlabs/prysm/issues/6076
* [ ] Teku https://github.com/PegaSysEng/teku/issues/2038
* [ ] Nimbus https://github.com/status-im/nim-beacon-chain/issues/1103

**Comment by q9f** [comment]
Bumping to v0.12.1 ...

**Comment by terencechain** [comment]
Prysm has aligned to v0.12.1
https://github.com/prysmaticlabs/prysm/issues/6076
https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0-alpha.10

**Comment by q9f** [comment]
Spec: https://github.com/goerli/altona/blob/master/altona.yaml

Contract: https://goerli.etherscan.io/address/0x16e82d77882a663454ef92806b7deca1d394810f
